CREATE TABLE IF NOT EXISTS `portal_saved_report_subscriptions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '订阅主键ID',
  `report_id` VARCHAR(64) NOT NULL COMMENT '关联的黄金报表ID',
  `user_id` BIGINT NOT NULL COMMENT '订阅创建人与定时执行用户ID',
  `schedule_type` VARCHAR(16) NOT NULL COMMENT '频率类型: daily, weekly, monthly, cron',
  `cron_expr` VARCHAR(64) NOT NULL COMMENT '标准五段Cron表达式',
  `timezone` VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai' COMMENT '调度时区',
  `params` JSON NULL COMMENT '定时运行使用的报表参数JSON',
  `ai_analysis_enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用AI智能分析',
  `analysis_instruction` TEXT NULL COMMENT '订阅级补充AI分析要求，最多500字',
  `notify_on_success` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '运行成功时是否生成通知',
  `notify_on_failure` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '运行失败时是否生成通知',
  `external_channels` JSON NULL COMMENT '启用的外部通知渠道数组',
  `status` VARCHAR(16) NOT NULL DEFAULT 'active' COMMENT '订阅状态: active, paused, error',
  `consecutive_failures` INT NOT NULL DEFAULT 0 COMMENT '连续失败次数',
  `last_run_id` BIGINT NULL COMMENT '最近一次运行历史ID',
  `last_run_at` DATETIME NULL COMMENT '最近一次运行时间',
  `next_run_at` DATETIME NULL COMMENT '下一次计划运行时间',
  `last_error` TEXT NULL COMMENT '最近一次运行或调度错误',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `ux_portal_saved_report_subscriptions_report` (`report_id`),
  KEY `idx_portal_saved_report_subscriptions_user` (`user_id`),
  KEY `idx_portal_saved_report_subscriptions_status` (`status`),
  CONSTRAINT `fk_portal_saved_report_subscriptions_report` FOREIGN KEY (`report_id`) REFERENCES `portal_saved_reports` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_portal_saved_report_subscriptions_user` FOREIGN KEY (`user_id`) REFERENCES `ai_agent_users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='黄金报表定时订阅配置表';

CREATE TABLE IF NOT EXISTS `portal_notifications` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '站内通知主键ID',
  `user_id` BIGINT NOT NULL COMMENT '通知接收用户ID',
  `category` VARCHAR(32) NOT NULL DEFAULT 'saved_report' COMMENT '通知业务分类',
  `level` VARCHAR(16) NOT NULL DEFAULT 'info' COMMENT '通知等级: success, warning, error, info',
  `title` VARCHAR(200) NOT NULL COMMENT '通知标题',
  `content` TEXT NULL COMMENT '通知摘要内容',
  `resource_type` VARCHAR(32) NULL COMMENT '关联资源类型',
  `resource_id` VARCHAR(64) NULL COMMENT '关联资源ID',
  `metadata` JSON NULL COMMENT '通知跳转和展示所需安全摘要JSON',
  `read_at` DATETIME NULL COMMENT '已读时间，为空表示未读',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_portal_notifications_user_created` (`user_id`, `created_at`),
  KEY `idx_portal_notifications_user_read` (`user_id`, `read_at`),
  CONSTRAINT `fk_portal_notifications_user` FOREIGN KEY (`user_id`) REFERENCES `ai_agent_users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='用户站内通知消息表';
